src/SellWeb.App/ViewModels/ProdutoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SellWeb.App.ViewModels
{
    public class ProdutoViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Fornecedor")]
        public Guid FornecedorId { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Nome { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(1000, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public decimal Valor { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DataCadastro { get; set; }

        [DisplayName("Ativo?")]
        public bool Ativo { get; set; }

        // Entity relations
        public FornecedorViewModel Fornecedor { get; set; }
        public IEnumerable<FornecedorViewModel> Fornecedores { get; set; }

    }
}

src/SellWeb.App/Controllers/ProdutosController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SellWeb.App.ViewModels;
using SellWeb.Business.Interfaces;
using SellWeb.Business.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SellWeb.App.Controllers
{
    [Authorize]
    public class ProdutosController : BaseController
    {
        private readonly IProdutoRepository _produtoRepo;
        private readonly IFornecedorRepository _fornecedorRepo;
        private readonly IProdutoService _produtoService;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;

        public ProdutosController(IProdutoRepository produtoRepo,
                                  IMapper mapper,
                                  IFornecedorRepository fornecedorRepo,
                                  IProdutoService produtoService,
                                  INotificador notificador,
                                  INotyfService notyf) : base(notificador)
        {
            _produtoRepo = produtoRepo;
            _mapper = mapper;
            _fornecedorRepo = fornecedorRepo;
            _produtoService = produtoService;
            _notyf = notyf;
        }

        [Route("lista-produtos")]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(await _produtoRepo.ObterProdutosFornecedores()));
        }

        [Route("detalhes-produto/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null) return NotFound();

            var produtoViewModel = await ObterProduto(id);

            if (produtoViewModel == null) return NotFound();

            return View(produtoViewModel);
        }

        [Route("criar-produto")]
        public async Task<IActionResult> Create()
        {
            var produtoViewModel = await PopularFornecedores(new ProdutoViewModel());
            return View(produtoViewModel);
        }

        [Route("criar-produto")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProdutoViewModel produtoViewModel)
        {
            produtoViewModel = await PopularFornecedores(produtoViewModel);

            if (!ModelState.IsValid) return View(produtoViewModel);

            await _produtoService.Adicionar(_mapper.Map<Produto>(produtoViewModel));

            if (!OperacaoValida()) return View(produtoViewModel);

            _notyf.Success("registro salvo com sucesso", 3);

            return RedirectToAction("Index");
        }

        [Route("editar-produto")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var produtoViewModel = await ObterProduto(id);

            if (produtoViewModel == null) return NotFound();

            return View(produtoViewModel);
        }

        [Route("editar-produto")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ProdutoViewModel produtoViewModel)
        {
            if (id != produtoViewModel.Id) return NotFound();

            var produtoAtualizacao = await ObterProduto(id);
            produtoViewModel.Fornecedor = produtoAtualizacao.Fornecedor;

            if (!ModelState.IsValid) return View(produtoViewModel);

            produtoAtualizacao.Nome = produtoViewModel.Nome;
            produtoAtualizacao.Descricao = produtoViewModel.Descricao;
            produtoAtualizacao.Valor = produtoViewModel.Valor;
            produtoAtualizacao.Ativo = produtoViewModel.Ativo;

            await _produtoService.Atualizar(_mapper.Map<Produto>(produtoAtualizacao));

            if (!OperacaoValida()) return View(produtoViewModel);

            _notyf.Success("registro salvo com sucesso", 3);

            return RedirectToAction("Index");
        }

        [Route("excluir-produto")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null) return NotFound();

            var produtoViewModel = await ObterProduto(id);

            if (produtoViewModel == null) return NotFound();

            return View(produtoViewModel);
        }

        [Route("excluir-produto")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var produto = await ObterProduto(id);
            if (produto == null) return NotFound();

            await _produtoService.Remover(id);

            if (!OperacaoValida()) return View(produto);

            _notyf.Success("produto excluído com sucesso", 3);

            return RedirectToAction("Index");
        }

        private async Task<ProdutoViewModel> ObterProduto(Guid id)
        {
            var produto = _mapper.Map<ProdutoViewModel>(await _produtoRepo.ObterProdutoFornecedor(id));
            await PopularFornecedores(produto);
            return produto;
        }

        private async Task<ProdutoViewModel> PopularFornecedores(ProdutoViewModel produto)
        {
            produto.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepo.ObterTodos());
            return produto;
        }
    }
}

src/SellWeb.App/Extensions/NotificacoesViewComponent.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using SellWeb.Business.Interfaces;
using System.Threading.Tasks;

namespace SellWeb.App.Extensions
{
    public class NotificacoesViewComponent : ViewComponent
    {
        private readonly INotificador _notificador;
        private readonly INotyfService _notyf;

        public NotificacoesViewComponent(INotificador notificador,
                                         INotyfService notyf)
        {
            _notificador = notificador;
            _notyf = notyf;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notificador.ObterNotificacao());

            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Mensagem));

            notificacoes.ForEach(c => _notyf.Error(c.Mensagem));

            return View();
        }
    }
}

src/SellWeb.App/Views/Produtos/Create.cshtml
@model SellWeb.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "novo produto";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <vc:notificacoes></vc:notificacoes>

            <div class="form-group">
                <label asp-for="FornecedorId" class="control-label"></label>
                <select asp-for="FornecedorId" class="form-control" asp-items="@(new SelectList(Model.Fornecedores, "Id", "Nome"))">
                    <option></option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea rows="4" asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="cadastrar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SellWeb.App/Views/Produtos/Delete.cshtml
@model SellWeb.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "excluir produto";
}

<h1>@ViewData["Title"]</h1>

<h3>esta ação é permanente!</h3>

<vc:notificacoes></vc:notificacoes>

<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fornecedor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fornecedor.Nome)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="excluir produto" class="btn btn-danger" />
        <a class="btn btn-info" asp-action="Index">voltar</a>
    </form>
</div>

src/SellWeb.App/Views/Produtos/Details.cshtml
@model SellWeb.App.ViewModels.ProdutoViewModel
@using SellWeb.App.Extensions

@{
    ViewData["Title"] = "detalhes do produto";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div>
    <dl class="row col-md-8">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fornecedor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fornecedor.Nome)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">editar produto</a>
    <a class="btn btn-info" asp-action="Index">voltar</a>
</div>

src/SellWeb.App/Views/Produtos/Edit.cshtml
@model SellWeb.App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "editar produto";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            <vc:notificacoes></vc:notificacoes>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="FornecedorId" class="control-label"></label><br />
                <label><b>@Model.Fornecedor.Nome</b></label>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea rows="4" asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="salvar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SellWeb.App/Views/Produtos/Index.cshtml
@model IEnumerable<SellWeb.App.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Lista de Produtos";
}

<h1>@ViewData["Title"]</h1>
<hr />

<p>
    <a class="btn btn-info" asp-action="Create">novo produto</a>
</p>

<partial name="_ListaProdutos" />

src/SellWeb.App/Views/Produtos/_ListaProdutos.cshtml
@model IEnumerable<SellWeb.App.ViewModels.ProdutoViewModel>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fornecedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Fornecedor.Nome)
    </td>
    <td>
        @item.Valor.ToString("C")
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Ativo)
    </td>
    <td class="text-right">
        <a class="btn btn-info" asp-controller="Produtos" asp-action="Details" asp-route-id="@item.Id">
            <span class="fa fa-search"></span>
        </a>
        <a class="btn btn-warning" asp-controller="Produtos" asp-action="Edit" asp-route-id="@item.Id">
            <span class="fa fa-pencil"></span>
        </a>
        <a class="btn btn-danger" asp-controller="Produtos" asp-action="Delete" asp-route-id="@item.Id">
            <span class="fa fa-trash"></span>
        </a>
    </td>
</tr>
}
    </tbody>
</table>